'use client'
import Link from "next/link";
import Head from "next/head";
import BackToSportsBanner from "@/components/BackToSportsBanner";
import "swiper/css";
import BackToSportsBottom from '@/components/BackToSportsBottom';

const BackToSportsPage = () => {

 
  return (
    <>
      <Head>
        <title>Stance Health</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BackToSportsBanner />
      <section className='sec running-program-sec'>
        <div className='container-fluid'>
          <div className='row'>
            <div className='col-md-12'>
               <div className='center-con center'>
                  <h3 className='sec-head'>Why Join <span>our Return to play</span> Program?</h3>
                  <p className='para'>Embark on a tailored journey back to your sport with Stance's personalized return-to-sports programs,<br /> meticulously crafted for a seamless and effective transition back to your pre-injury performance levels. Guided by<br /> evidence-based protocols, we prioritize understanding your sport-specific needs, leveraging your strengths and<br /> addressing any gaps to pave the way for a confident return to peak performance.</p>
               </div>
            </div>
          </div>
        </div>
        <div className='running-program-row running-program-row-1'>
            <img className='r-line' src='/assets/images/r-line-1.svg' />
          <div className='container'>
            <div className='col-md-12'>
            <div className='the-grid three'>
                 <div className='running-program-div'>
                    <img src="/assets/images/sports-icon-1.svg" />
                    <h3>Identify & <br /> understand<br /> injury<br /> pathways</h3>
                 </div>
                 <div className='running-program-div'>
                    <img src="/assets/images/sports-icon-2.svg" />
                    <h3>Assisted<br /> therapy to<br /> minimize pain<br /> during sport</h3>
                 </div>
                 <div className='running-program-div'>
                    <img src="/assets/images/sports-icon-3.svg" />
                    <h3>Maximize mobility<br /> for Sport</h3>
                 </div>
               </div>
            </div>
          </div>
        </div>
        <div className='running-program-row'>
            <img className='r-line r-line-2' src='/assets/images/r-line-2.svg' />
          <div className='container'>
            <div className='col-md-12'>
            <div className='the-grid two'>
                 <div className='running-program-div'>
                    <img src="/assets/images/sports-icon-4.svg" />
                    <h3>Workload<br /> monitoring<br /> to avoid over<br /> or under<br /> training</h3>
                 </div>
                 <div className='running-program-div'>
                    <img src="/assets/images/sports-icon-5.svg" />
                    <h3>Enhanced<br /> performance<br /> beyond pre-<br />injury levels</h3>
                 </div>
               </div>
            </div>
          </div>
        </div>
      </section>
          <BackToSportsBottom />

      <section className='running-cta sec'>
        <div className='container'>
         <img className='cta-bg' src="/assets/images/bts-cta.svg" />
          <div className='row items-center'>
            <div className='col-md-8'>
              <div className='cta-side'>
                <h3 className='sec-head sm'>Ready to level up your game?</h3>
                <p className='para'>Reserve your spot now and experience firsthand how our Return to Play programs empower you to achieve your athletic goals with confidence</p>
              </div>
            </div>
            <div className='col-md-3 offset-md-1 right'>
            <a href="https://dashboard.stance.health/onboarding-patient?utm_source=website&utm_medium=cta&utm_campaign=website_booking" target="_blank" rel="noreferrer" className='main-btn big'>
                                <span>Book Now</span>
                            </a>
            </div>
          </div>
        </div>
      </section>
    </>
  )
}

export default BackToSportsPage