'use client'
import Link from "next/link";
import Head from "next/head";
import InjuryManagementBanner from "@/components/InjuryManagementBanner";
import "swiper/css";
import InjuryManagementBottom from '@/components/InjuryManagementBottom';

const InjuryManagementPage = () => {

 
  return (
    <>
      <Head>
        <title>Stance Health</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <InjuryManagementBanner />
      <section className='sec running-program-sec'>
        <div className='container-fluid'>
          <div className='row'>
            <div className='col-md-12'>
               <div className='center-con center'>
                  <h3 className='sec-head'>Why Join <span>our Pain Management</span> Program?</h3>
                  <p className='para'>At Stance, we prioritize accurate diagnosis as the cornerstone of effective injury and pain management. Our<br /> advanced clinical and technology-based evaluations allow us to identify the root cause and contributing factors.<br /> Not only does this help in recovery but helps prevent future injuries.</p>
               </div>
                  
            </div>
          </div>
        </div>
        <div className='running-program-row running-program-row-1'>
            <img className='r-line' src='/assets/images/r-line-1.svg' />
          <div className='container'>
            <div className='col-md-12'>
            <div className='the-grid three'>
                 <div className='running-program-div'>
                    <img src="/assets/images/injury-icon-1.svg" />
                    <h3>Identify root<br /> cause and<br /> risks of pain</h3>
                 </div>
                 <div className='running-program-div'>
                    <img src="/assets/images/injury-icon-2.svg" />
                    <h3>Manage the<br /> source of<br /> symptoms</h3>
                 </div>
                 <div className='running-program-div'>
                    <img src="/assets/images/injury-icon-3.svg" />
                    <h3>Educate on<br /> factors<br /> contributing to<br /> pain</h3>
                 </div>
               </div>
            </div>
          </div>
        </div>
        <div className='running-program-row'>
            <img className='r-line r-line-2' src='/assets/images/r-line-2.svg' />
          <div className='container'>
            <div className='col-md-12'>
            <div className='the-grid two'>
                 <div className='running-program-div'>
                    <img src="/assets/images/injury-icon-4.svg" />
                    <h3>Programs to<br /> minimize<br /> injury and<br /> surgical risks</h3>
                 </div>
                 <div className='running-program-div'>
                    <img src="/assets/images/injury-icon-5.svg" />
                    <h3>AI-powered<br /> at-home self-<br />paced<br /> recovery<br /> pathways</h3>
                 </div>
               </div>
            </div>
          </div>
        </div>
      </section>
          <InjuryManagementBottom />

      <section className='running-cta sec'>
        <div className='container'>
         <img className='cta-bg' src="/assets/images/im-cta.svg" />
          <div className='row items-center'>
            <div className='col-md-8'>
              <div className='cta-side'>
                <h3 className='sec-head sm'>Experience pain-free living</h3>
                <p className='para'>By trusting our proven injury and pain management programs</p>
              </div>
            </div>
            <div className='col-md-3 offset-md-1 right'>
            <a href="https://book.stance.health/stance-health" target="_blank" rel="noreferrer" className='main-btn big'>
                                <span>Book Now</span>
                            </a>
            </div>
          </div>
        </div>
      </section>
    </>
  )
}

export default InjuryManagementPage