'use client'
import Link from "next/link";
import Head from "next/head";
import PerformanceTrainingBanner from "@/components/PerformanceTrainingBanner";
import "swiper/css";
import PerformanceTrainingBottom from '@/components/PerformanceTrainingBottom';

const PerformanceTrainingPage = () => {

 
  return (
    <>
      <Head>
        <title>Stance Health</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PerformanceTrainingBanner />
      <section className='sec running-program-sec'>
        <div className='container-fluid'>
          <div className='row'>
            <div className='col-md-12'>
               <div className='center-con center'>
                  <h3 className='sec-head'>Why Join <span>our performance enhancement</span> Program?</h3>
                  <p className='para'>Engaging in regular physical activity offers numerous benefits, including improved cardiovascular health, increased<br /> muscular strength, endurance, enhanced mobility, and better mental health.<br /> A structured regimen built by experts ensures your progress without plateaus. Staying active also helps reduce the risk<br /> of chronic diseases such as heart disease, diabetes, obesity and more</p>
               </div>
            </div>
          </div>
        </div>
        <div className='running-program-row running-program-row-1'>
            <img className='r-line' src='/assets/images/r-line-1.svg' />
          <div className='container'>
            <div className='col-md-12'>
            <div className='the-grid three'>
                 <div className='running-program-div'>
                    <img src="/assets/images/performance-icon-1.svg" />
                    <h3>Manage risks<br /> of lifestyle<br /> disorders</h3>
                 </div>
                 <div className='running-program-div'>
                    <img src="/assets/images/performance-icon-2.svg" />
                    <h3>Data-backed<br /> progress<br /> monitoring</h3>
                 </div>
                 <div className='running-program-div'>
                    <img src="/assets/images/performance-icon-3.svg" />
                    <h3>Multi-disciplinary<br /> evidence-based<br /> plans</h3>
                 </div>
               </div>
            </div>
          </div>
        </div>
        <div className='running-program-row'>
            <img className='r-line r-line-2' src='/assets/images/r-line-2.svg' />
          <div className='container'>
            <div className='col-md-12'>
            <div className='the-grid two'>
                 <div className='running-program-div'>
                    <img src="/assets/images/performance-icon-4.svg" />
                    <h3>Goal-<br />oriented<br /> regimens and<br /> at-home<br /> support</h3>
                 </div>
                 <div className='running-program-div'>
                    <img src="/assets/images/performance-icon-5.svg" />
                    <h3>Improved<br /> athleticism</h3>
                 </div>
               </div>
            </div>
          </div>
        </div>
      </section>
          <PerformanceTrainingBottom />

      <section className='running-cta sec'>
        <div className='container'>
         <img className='cta-bg' src="/assets/images/pt-cta.svg" />
          <div className='row items-center'>
            <div className='col-md-8'>
              <div className='cta-side'>
                <h3 className='sec-head sm'>Want to break the glass ceiling?</h3>
                <p className='para'>Experience the transformative journey to an active life</p>
              </div>
            </div>
            <div className='col-md-3 offset-md-1 right'>
            <a href="https://dashboard.stance.health/onboarding-patient" target="_blank" rel="noreferrer" className='main-btn big'>
                                <span>Book Now</span>
                            </a>
            </div>
          </div>
        </div>
      </section>
    </>
  )
}

export default PerformanceTrainingPage