'use client'
import Link from "next/link";
import Head from "next/head";
import SurgicalRehabBanner from "@/components/SurgicalRehabBanner";
import SurgicalRehabBottom from '@/components/SurgicalRehabBottom';

const SurgicalRehabPage = () => {

 
  return (
    <>
      <Head>
        <title>Stance Health</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SurgicalRehabBanner />
      <section className='sec running-program-sec'>
        <div className='container-fluid'>
          <div className='row'>
            <div className='col-md-12'>
               <div className='center-con center'>
                  <h3 className='sec-head'>Why Join <span>our Surgical rehab</span> Program?</h3>
                  <p className='para'>Stance's pre and post-operative rehab programs are meticulously structured to support individuals in resuming <br /> their activities after surgery. Our comprehensive approach combines a milestone-based methodology with manual <br /> techniques, targeted exercises, and personalized interventions tailored to each surgery type. Post-operative <br /> rehabilitation is specifically designed to optimize healing, restore function, and enable a seamless return to pre-<br />surgery levels of activity and performance.</p>
               </div>
                  
            </div>
          </div>
        </div>
        <div className='running-program-row running-program-row-1'>
            <img className='r-line' src='/assets/images/r-line-1.svg' />
          <div className='container'>
            <div className='col-md-12'>
            <div className='the-grid three'>
                 <div className='running-program-div'>
                    <img src="/assets/images/s-1.png" />
                    <h3>Pre-op Rehab<br /> for ease of<br /> post-surgical<br /> healing</h3>
                 </div>
                 <div className='running-program-div'>
                    <img src="/assets/images/s-2.png" />
                    <h3>Data-backed<br /> recovery<br /> pathways</h3>
                 </div>
                 <div className='running-program-div'>
                    <img src="/assets/images/s-3.png" />
                    <h3>Expert-led manual<br /> therapy to restore<br /> range of motion</h3>
                 </div>
               </div>
            </div>
          </div>
        </div>
        <div className='running-program-row'>
            <img className='r-line r-line-2' src='/assets/images/r-line-2.svg' />
          <div className='container'>
            <div className='col-md-12'>
            <div className='the-grid two'>
                 <div className='running-program-div'>
                    <img src="/assets/images/s-4.png" />
                    <h3>Mobility<br /> regimens for<br /> return to<br /> function</h3>
                 </div>
                 <div className='running-program-div'>
                    <img src="/assets/images/s-5.png" />
                    <h3>Goal-based<br /> strength-<br />building to<br /> minimize<br /> relapse</h3>
                 </div>
               </div>
            </div>
          </div>
        </div>
      </section>
          <SurgicalRehabBottom />

      <section className='running-cta sec'>
        <div className='container'>
         <img className='cta-bg' src="/assets/images/sr-cta.svg" />
          <div className='row items-center'>
            <div className='col-md-8'>
              <div className='cta-side'>
                <h3 className='sec-head sm'>Experience life without fear of pain.</h3>
                <p className='para'>Our surgical rehab programs are designed to restore your back to your old self!</p>
              </div>
            </div>
            <div className='col-md-3 offset-md-1 right'>
            <a href="https://book.stance.health/stance-health" target="_blank" rel="noreferrer" className='main-btn big'>
                                <span>Book Now</span>
                            </a>
            </div>
          </div>
        </div>
      </section>
    </>
  )
}

export default SurgicalRehabPage